const panels = [
  { name: "Trex IPTV", rating: 4.9, channels: "42,500+", movies: "110,000+", series: "18,500+", description: "Most popular panel with largest library.", features: ["4K/8K Streaming", "Anti-freeze", "M3U + MAG"], subPrice: "€49/year", resellerCredits: "120 Credits", resellerPrice: "€185", creditRule: "12 credits = 1 year" },
  { name: "8K Strong", rating: 4.9, channels: "34,261+", movies: "123,499+", series: "0", description: "Premium 8K streaming, instant activation.", features: ["8K Streaming", "Global CDN", "Catch-up"], subPrice: "€50/year", resellerCredits: "120 Credits", resellerPrice: "€190", creditRule: "12 credits = 1 year" },
  { name: "Dino IPTV", rating: 4.5, channels: "29,800+", movies: "75,000+", series: "10,000+", description: "Affordable panel with free trial.", features: ["Affordable", "EPG Support", "Multi-device"], subPrice: "€40/year", resellerCredits: "120 Credits", resellerPrice: "€100", creditRule: "12 credits = 1 year" },
  { name: "Lion OTT", rating: 4.7, channels: "18,484+", movies: "86,126+", series: "22,555+", description: "Stable streaming, large VOD library.", features: ["Multi-Device", "Large VOD", "24/7 Support"], subPrice: "€45/year", resellerCredits: "10 Credits", resellerPrice: "€85", creditRule: "1 credit = 1 year" },
  { name: "Crystal OTT", rating: 4.7, channels: "33,500+", movies: "90,000+", series: "13,000+", description: "Clear stream, anti-freeze technology.", features: ["Anti-freeze", "Quick Support", "1 Credit/Year"], subPrice: "€45/year", resellerCredits: "10 Credits", resellerPrice: "€110", creditRule: "1 credit = 1 year" },
  { name: "Magnum OTT", rating: 4.8, channels: "21,141+", movies: "106,175+", series: "0", description: "Very stable for USA/Canada.", features: ["USA Stable", "Free Apps", "High Uptime"], subPrice: "€45/year", resellerCredits: "10 Credits", resellerPrice: "€140", creditRule: "1 credit = 1 year" },
  { name: "Dream 4K", rating: 4.9, channels: "39,800+", movies: "102,000+", series: "18,000+", description: "Ultra HD 4K/8K, Dolby Audio.", features: ["4K/8K", "No Buffering", "PPV Events"], subPrice: "€55/year", resellerCredits: "120 Credits", resellerPrice: "€145", creditRule: "12 credits = 1 year" },
  { name: "Eagle IPTV", rating: 4.7, channels: "12,620+", movies: "42,005+", series: "9,419+", description: "Stable streaming, fast activation.", features: ["Fast Activation", "Catch-up", "Reseller Friendly"], subPrice: "€40/year", resellerCredits: "120 Credits", resellerPrice: "€95", creditRule: "12 credits = 1 year" },
  { name: "ProMax", rating: 4.8, channels: "36,200+", movies: "95,000+", series: "14,000+", description: "Max speed CDN, auto setup.", features: ["Max Speed CDN", "Auto Setup", "PPV Events"], subPrice: "€45/year", resellerCredits: "120 Credits", resellerPrice: "€185", creditRule: "12 credits = 1 year" },
  { name: "Tivione", rating: 4.5, channels: "28,700+", movies: "68,000+", series: "8,000+", description: "Tivimate compatible, easy install.", features: ["Tivimate Compatible", "Easy Install", "Affordable"], subPrice: "€40/year", resellerCredits: "10 Credits", resellerPrice: "€199", creditRule: "1 credit = 1 year" },
  { name: "Mega OTT", rating: 4.8, channels: "28,500+", movies: "95,000+", series: "12,000+", description: "Vast content library, stable.", features: ["Stable Streaming", "Large VOD", "24/7 Support"], subPrice: "€48/year", resellerCredits: "10 Credits", resellerPrice: "€95", creditRule: "1 credit = 1 year" },
  { name: "Infinity IPTV", rating: 4.8, channels: "37,800+", movies: "110,000+", series: "20,000+", description: "Endless content, live sports.", features: ["Latest Movies", "Live Sports", "Catch-up"], subPrice: "€50/year", resellerCredits: "10 Credits", resellerPrice: "€200", creditRule: "1 credit = 1 year" },
  { name: "Max OTT", rating: 4.6, channels: "31,200+", movies: "82,000+", series: "11,000+", description: "Maximum channels, API access.", features: ["Maximum Channels", "API Access", "12 Credits/Year"], subPrice: "€45/year", resellerCredits: "120 Credits", resellerPrice: "€130", creditRule: "12 credits = 1 year" },
  { name: "Nexon IPTV", rating: 4.7, channels: "17,200+", movies: "120,000+", series: "0", description: "Best-selling in Spain & Latin America.", features: ["Fast Activation", "Easy Management", "Large VOD"], subPrice: "€45/year", resellerCredits: "120 Credits", resellerPrice: "€100", creditRule: "12 credits = 1 year" }
];
